### ISSUE TITLE
Correct way to install Sonnet gpu version (>= 1.26) and tensorflow probability >= 0.5.0

### ISSUE THREAD

**Issue by JCMiles** [deepmind/sonnet#119] opened 2019-02-11 17:16 UTC
Hello DM team.
I'm running a project on gcloud and I need some clarification about installation and dependencies.
In the beginning I built my model on a dev machine with only CPU and dm-sonnet 1.26 and everything went fine.
Than few days ago I was ready to train it so I moved to a new vm instance with 2 tesla P100 , python 3.5 and tensorflow-gpu 1.12 pre-installed. I've tried to update Sonnet to the latest version (1.29) and obviously I wanted to install the gpu version. Seems like the latest gpu version of Sonnet still the 1.26 (am I wrong ?) 

My problem is here.
The installation process by pip3 crashes cause sonnet requires tensorflow-probability-gpu >= 0.4
and I get the message that there is no version that satisfies this requirement.
so I did some research and I discovered that from version 0.5 tensorflow-probability and 
tensorflow-probability-gpu were merged in the same package.

So my first question is: what's the right procedure to install the latest Sonnet-gpu version?

second question: as a workaround (just cause I don't wanna be stucked)
I've installed tensorflow-probaility 0.5.0 (that is the official version compatible with tf 1.12)
and than I installed dm-sonnet (CPU) using pip3.

I ran a train cycle just to check the workflow, I was expecting some errors (cause I didn't installed the right sonnet gpu version) but unexpectedly everything went fine. The input pipeline is showing optimal performance during the training on 2 GPUs the only thig is that while I'm building the model
I recive a lot of deprecation warnings from numpy (i got the 1.16.1 version installed) like the following one.

/home/manuel_migliazza/.local/lib/python3.5/site-packages/numpy/lib/type_check.py:546: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  'a.item() instead', DeprecationWarning, stacklevel=1)

**Comment by diegolascasas** [comment] 2019-02-11 18:29
Hi @JCMiles, thanks for flagging this.

Can you test your setup with `dm-sonnet` (non-GPU)?

The reason we created the two versions was due to some custom ops that we developed and needed separate builds. We ended up merging them to Tensorflow contrib after a while, so `dm-sonnet` and `dm-sonnet-gpu` are currently identical, except for the dependencies. `dm-sonnet` works with both `tensorflow` and `tensorflow-gpu`, so it should be what you're looking for. 

Please tell us if this works for you. 
Meanwhile we'll address the dependency issue to make sure `dm-sonnet-gpu` works for all users.

**Comment by JCMiles** [comment] 2019-02-11 22:43
Hi @diegolascasas , thx for the replay.

I can confirm that with the following configuration:
- tensorflow 1.12
- tesnsorflow-probability 0.5.0
- dm-sonnet 1.29 (non-GPU)

Everything's fine !
The only annoying thing still the deprecation warnings  (a lots of them)  I posted  previously
if you have numpy 1.16.1

**Comment by malcolmreynolds** [comment] 2019-02-12 12:51
@JCMiles glad to hear things are working. About the deprecation warnings, as far as I can see we are not calling np.asscalar anywhere in Sonnet, so I believe those warnings are coming from something else (maybe TF). If there are other specific deprecated functions please post which ones, and I can see if we are causing any of them. Note that fixing these might not be possible in the short term, as Sonnet primarily needs to support the version of Numpy used in google's internal repository, which is not yet at 1.16.

**Comment by JCMiles** [comment] 2019-02-12 14:35
@ malcolmreynolds warnings are coming from tf-probability when I build the model.
can you please tell me wich is the current numpy version on gcloud?
I think the update to numpy 1.16 was made when I installed tf-probability 0.5.0
I currently investigating about that.

**Comment by JCMiles** [comment] 2019-02-13 10:42
@diegolascasas @malcolmreynolds 
after downgrading numpy 1.16 to numpy 1.15.4 I was able to remove those deprecation warnings

but I'm still getting this one:

/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/tf_inspect.py:75: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  return _inspect.getargspec(target)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

could you plis check it?

**Comment by csherstan** [comment] 2019-03-16 18:08
Regarding the problem of installing dm-sonnet-gpu. I'm seeing a problem with this as well, but I believe the issue is a misspecified package. Here is the output of the `pip install dm-sonnet-gpu` command:
```
Collecting tensor-probability-gpu>=0.4.0 (from dm-sonnet-gpu)
  Could not find a version that satisfies the requirement tensor-probability-gpu>=0.4.0 (from dm-sonnet-gpu) (from versions: )
No matching distribution found for tensor-probability-gpu>=0.4.0 (from dm-sonnet-gpu)
```

Notice that it's looking for `tensor-probability-gpu` but the correct package is `tensorflow-probability-gpu`.

**Comment by CompliceU** [comment] 2019-03-26 13:55
hi,i have got the same problem ,did U know how to do ? @JCMiles @malcolmreynolds

**Comment by tomhennigan** [comment] 2019-03-26 17:24
I believe this is fixed in b18ca77dd which should be part of `dm-sonnet-gpu==1.29` but unfortunately that wasn't pushed along with `dm-sonnet` (unsure why, will ask around).

As a workaround, I'd suggest the following:

```shell
$ pip uninstall dm-sonnet-gpu
$ pip install dm-sonnet>=1.29 tensorflow-gpu tensorflow-probability-gpu
```

Since Sonnet no longer has any C++ code `dm-sonnet` and `dm-sonnet-gpu` are actually identical apart from requirements on GPU variants of TF and TFP. I think going forward we plan to deprecate `dm-sonnet-gpu` and suggest users pip install the GPU variants of TF if they want.

**Comment by UCC-team** [comment] 2019-04-11 07:46
>>> import sonnet
WARNING:tensorflow:From /root/miniconda3/lib/python3.7/site-packages/tensorflow_probability/python/distributions/deterministic.py:386: RegisterKL.__init__ (from tensorflow.python.ops.distributions.kullback_leibler) is deprecated and will be removed after 2019-01-01.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/sonnet/__init__.py", line 47, in _ensure_dependency_available_at_version
    pkg = importlib.import_module(package_name)
  File "/root/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/miniconda3/lib/python3.7/site-packages/tensorflow_probability/__init__.py", line 21, in <module>
    from tensorflow_probability.python import *  # pylint: disable=wildcard-import
  File "/root/miniconda3/lib/python3.7/site-packages/tensorflow_probability/python/__init__.py", line 22, in <module>
    from tensorflow_probability.python import distributions
  File "/root/miniconda3/lib/python3.7/site-packages/tensorflow_probability/python/distributions/__init__.py", line 77, in <module>
    from tensorflow_probability.python.distributions.vector_diffeomixture import quadrature_scheme_softmaxnormal_gauss_hermite
  File "/root/miniconda3/lib/python3.7/site-packages/tensorflow_probability/python/distributions/vector_diffeomixture.py", line 28, in <module>
    from tensorflow.contrib.linalg.python.ops import linear_operator_addition as linop_add_lib
ModuleNotFoundError: No module named 'tensorflow.contrib.linalg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/lib/python3.7/site-packages/sonnet/__init__.py", line 64, in <module>
    _ensure_dependency_available_at_version('tensorflow_probability', '0.4.0')
  File "/root/miniconda3/lib/python3.7/site-packages/sonnet/__init__.py", line 54, in _ensure_dependency_available_at_version
    package_name, min_version, pip_name, pip_name))
SystemError: Sonnet requires tensorflow_probability (minimum version 0.4.0) to be installed. If using pip, run `pip install tensorflow-probability` or `pip install tensorflow-probability-gpu`

**Comment by malcolmreynolds** [comment] 2019-04-23 16:10
@UCC-team what versions of Sonnet & TF are you working with? I remember seeing that error a while back and it was to do with non-matching versions of TF and TFP. Right now in a fresh virtualenv, I can run `pip install tensorflow tensorflow-probability dm-sonnet` and I get a working setup.

As noted above, `dm-sonnet-gpu` is no longer updated as all the GPU specific code was upstreamed into TF. I just pushed a final dummy package to pypi, so that if a user installs dm-sonnet-gpu they get an error on importing which says to use dm-sonnet instead.

**Comment by tomhennigan** [comment] 2020-04-17 09:19
Closing out some old issues, please reopen if this is still a blocker.

**Closed by tomhennigan** 2020-04-17 09:19 UTC
