### ISSUE TITLE
Bazel build failure on Ubuntu

### ISSUE THREAD

**Issue by johnnogent** [deepmind/sonnet#9] opened 2017-04-08 18:21 UTC
I have a failure when running 
bazel build --config=opt :install
on Ubuntu

**Comment by cgarciae** [comment] 2017-04-09 14:14
Same here on Ubuntu 16.10.

**Comment by johnnogent** [comment] 2017-04-09 17:42
same on Ubuntu 14.04 TLS

**Comment by leesunfreshing** [comment] 2017-04-10 09:54
same here. Ubuntu 16.04 LTS

**Comment by normanheckscher** [comment] 2017-04-10 09:57
Builds on local ubuntu 16.04 LTS after applying https://github.com/deepmind/sonnet/pull/6

**Comment by leesunfreshing** [comment] 2017-04-10 15:14
@normanheckscher problem solved, thx

**Comment by malcolmreynolds** [comment] 2017-04-10 19:42
@normanheckscher thanks for the fix - we'll get it in ASAP, and I'll close this issue once the changes are pushed back out to GitHub.

**Comment by malcolmreynolds** [comment] 2017-04-19 16:37
@normanheckscher @leesunfreshing @johnnogent @cgarciae  We have pushed a fix, please can you try and build again?

**Comment by normanheckscher** [comment] 2017-04-19 22:47
@malcolmreynolds It builds, I just can't import it. I'll try and look a little further into it sometime over the next few days when I get more time.

Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sonnet as snt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/norman/.virtualenvs/tf/local/lib/python2.7/site-packages/sonnet/__init__.py", line 102, in <module>
    from sonnet.python.ops.resampler import resampler
  File "/home/norman/.virtualenvs/tf/local/lib/python2.7/site-packages/sonnet/python/ops/resampler.py", line 33, in <module>
    tf.resource_loader.get_path_to_datafile("_resampler.so"))
  File "/home/norman/.virtualenvs/tf/local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: /home/norman/.virtualenvs/tf/local/lib/python2.7/site-packages/sonnet/python/ops/_resampler.so: undefined symbol: _ZN10tensorflow15shape_inference16InferenceContext15WithRankAtLeastENS0_11ShapeHandleEiPS2_
>>>

**Comment by normanheckscher** [comment] 2017-04-20 03:04
Managed to get it to work.
My separately installed tensorflow version (outside the sonnet directory) was originally form the head and a version of 1.1.0rc2. I changed this tensorflow version with git, recompiled and installed the resultant tensorflow-1.1.0rc1-cp27-cp27mu-linux_x86_64.whl. After this, sonnet build, installs and runs as expected.

`cd ~/workspace/tensorflow`
`git checkout r1.1`
`./configure`
`bazel build -c opt --copt=-mavx --copt=-mfpmath=both --copt=-msse4.2 --copt=-msse4.1 --config=cuda -k //tensorflow/tools/pip_package:build_pip_package --verbose_failures`
`bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp//tensorflow_pkg/`
`pip install --upgrade /tmp/tensorflow_pkg/tensorflow-1.1.0rc1-cp27-cp27mu-linux_x86_64.whl`
`cd ~/workspace`
`git clone --recursive https://github.com/deepmind/sonnet`
`etc etc etc from the sonnet instructions`

**Comment by thomkeh** [comment] 2017-04-21 10:11
I have the same error as @normanheckscher ("undefined symbol: ZN10tensorflow...") but my tensorflow is simply 1.0.1 from pip and I'm using Python3. So whatever @normanheckscher thinks was the problem, can't be the problem.

**Comment by normanheckscher** [comment] 2017-04-21 10:29
@thomkeh I managed to get it working by being very particular with my tensorflow install. I'm guessing that the issue lies somewhere around interoperability with Tensorflow as I've played with differing versions of TensorFlow in both the sonnet directory and in my workstation environment (using virtualenv).

After building and installing an older version of Tensorflow I have been able to get Sonnet running. I'd suggest using git to build tensorflow @ 36a47f2, as this is the version which Sonnet is linked against. I'm currently using it to bang out multi-cpu models with mnist... variable success (pun intended)... so yeah, it does work.

Is python 3 supported?

**Comment by thomkeh** [comment] 2017-04-21 10:35
@normanheckscher Ok, I see. Thanks for the response! I makes sense that you should use the tensorflow version that this repository links against.

Python3 is not officially supported but #10 made it sound like compatibility is just some small code changes away.

**Comment by adeze** [comment] 2017-05-18 04:58
```
	sudo apt-get dist-upgrade
```

fixed it for me on ubuntu 14.04 LTS

i found the bazel error fix elsewhere and it was stated it was an earlier version kernel issue

**Comment by kosklain** [comment] 2017-05-25 13:26
@thomkeh python 3 is supported now :)

Regarding the compilation issues, marking this as duplicate of #25 to follow progress there.

**Closed by kosklain** 2017-05-25 13:26 UTC
