### ISSUE TITLE
Build fails on Ubuntu 16.04.1

### ISSUE THREAD

**Issue by schani** [deepmind/sonnet#16] opened 2017-04-12 18:42 UTC
I followed the instructions, and got this error when building:

```
ubuntu@BorisGPUMP2 [ /tmp/sonnet ]  (master)
[18:35]: bazel build --config=opt :install
zsh: correct 'build' to 'BUILD' [nyae]? n
.............
WARNING: Config values are not defined in any .rc file: opt
WARNING: /home/ubuntu/.cache/bazel/_bazel_ubuntu/73ef796d701fb86018fd94fe895372e2/external/org_tensorflow/tensorflow/workspace.bzl:72:5: tf_repo_name was specified to tf_workspace but is no longer used and will be removed in the future.
INFO: Found 1 target...
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/73ef796d701fb86018fd94fe895372e2/external/protobuf/BUILD:241:1: C++ compilation of rule '@protobuf//:js_embed' failed: Process exited with status 1 [sandboxed].
src/main/tools/linux-sandbox-pid1.cc:257: "mount(/tmp/sonnet, tmp/sonnet, NULL, MS_BIND, NULL)": No such file or directory
Use --strategy=CppCompile=standalone to disable sandboxing for the failing actions.
Target //:install failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/73ef796d701fb86018fd94fe895372e2/external/org_tensorflow/tensorflow/core/BUILD:190:1 C++ compilation of rule '@protobuf//:js_embed' failed: Process exited with status 1 [sandboxed].
INFO: Elapsed time: 8.429s, Critical Path: 0.18s
```

```
[18:39]: lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
```

**Comment by ibab** [comment] 2017-04-13 10:18
It looks like bazel has a problem with sandboxing on your machine.
Can you tru re-running the command with
```
--genrule_strategy=standalone --spawn_strategy=standalone
```
added to the command line?

**Comment by schani** [comment] 2017-04-13 17:49
This, together with #6, made the build succeed, but after installing the wheel file, it seems like it can't find the native library:

```
[17:41]: python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import sonnet as snt
>>> import tensorflow as tf
>>> snt.resampler(tf.constant([0.]), tf.constant([0.]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/p27-tf1/lib/python2.7/site-packages/sonnet/python/ops/resampler.py", line 62, in resampler
    raise ImportError("_gen_resampler could not be imported.")
ImportError: _gen_resampler could not be imported.
```

The wheel file also doesn't contain a native library:

```
[17:44]: unzip -l ./sonnet-install/sonnet-1.0-py2-none-any.whl  | less
Archive:  ./sonnet-install/sonnet-1.0-py2-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
     4817  2017-04-13 17:41   sonnet/__init__.py
     8064  2017-04-13 17:41   sonnet/examples/dataset_shakespeare.py
      809  2017-04-13 17:41   sonnet/examples/__init__.py
    11702  2017-04-13 17:41   sonnet/examples/rnn_shakespeare.py
     3751  2017-04-13 17:41   sonnet/examples/module_with_build_args.py
   892315  2017-04-13 17:41   sonnet/examples/data/ts.train.txt
   111539  2017-04-13 17:41   sonnet/examples/data/ts.valid.txt
   111540  2017-04-13 17:41   sonnet/examples/data/ts.test.txt
      844  2017-04-13 17:41   sonnet/python/__init__.py
     5452  2017-04-13 17:41   sonnet/python/modules/experimental.py
    15044  2017-04-13 17:41   sonnet/python/modules/base.py
     7712  2017-04-13 17:41   sonnet/python/modules/pondering_rnn.py
    13392  2017-04-13 17:41   sonnet/python/modules/rnn_core.py
    20102  2017-04-13 17:41   sonnet/python/modules/batch_norm.py
     7109  2017-04-13 17:41   sonnet/python/modules/embed.py
    12396  2017-04-13 17:41   sonnet/python/modules/util.py
      829  2017-04-13 17:41   sonnet/python/modules/__init__.py
     7812  2017-04-13 17:41   sonnet/python/modules/block_matrix.py
     7402  2017-04-13 17:41   sonnet/python/modules/attention.py
     2053  2017-04-13 17:41   sonnet/python/modules/clip_gradient.py
   105355  2017-04-13 17:41   sonnet/python/modules/conv.py
     2044  2017-04-13 17:41   sonnet/python/modules/scale_gradient.py
    34392  2017-04-13 17:41   sonnet/python/modules/gated_rnn.py
    19266  2017-04-13 17:41   sonnet/python/modules/basic_rnn.py
    23212  2017-04-13 17:41   sonnet/python/modules/spatial_transformer.py
     3510  2017-04-13 17:41   sonnet/python/modules/sequential.py
    43211  2017-04-13 17:41   sonnet/python/modules/basic.py
    21282  2017-04-13 17:41   sonnet/python/modules/nets/convnet.py
    10619  2017-04-13 17:41   sonnet/python/modules/nets/alexnet.py
     1301  2017-04-13 17:41   sonnet/python/modules/nets/__init__.py
     8110  2017-04-13 17:41   sonnet/python/modules/nets/mlp.py
    13456  2017-04-13 17:41   sonnet/python/modules/nets/dilation.py
   264952  2017-04-13 17:41   sonnet/python/ops/_resampler.so
    10734  2017-04-13 17:41   sonnet/python/ops/nest.py
      833  2017-04-13 17:41   sonnet/python/ops/__init__.py
     3377  2017-04-13 17:41   sonnet/python/ops/initializers.py
     2860  2017-04-13 17:41   sonnet/python/ops/resampler.py
       10  2017-04-13 17:41   sonnet-1.0.dist-info/DESCRIPTION.rst
     1134  2017-04-13 17:41   sonnet-1.0.dist-info/metadata.json
        7  2017-04-13 17:41   sonnet-1.0.dist-info/top_level.txt
       92  2017-04-13 17:41   sonnet-1.0.dist-info/WHEEL
      888  2017-04-13 17:41   sonnet-1.0.dist-info/METADATA
     3867  2017-04-13 17:41   sonnet-1.0.dist-info/RECORD
---------                     -------
  1819196                     43 files
```

**Comment by fivejjs** [comment] 2017-04-20 14:40
I got the same error as @schani for both Python 2.7 and Python 3.6

**Comment by yukoga** [comment] 2017-04-22 12:25
While I got the same error as reported, resolved with moving out from build directory. 

$ git clone https://github.com/deepmind/sonnet.git
$ cd sonnet/tensorflow
$ ./configure
$ cd ../
$ mkdir /tmp/sonnet
$ bazel build --config=opt :install
$ ./bazel-bin/install /tmp/sonnet
$ pip install /tmp/sonnet/*.whl
$ python

>>> import sonnet as snt
>>> import tensorflow as tf
>>> snt.resampler(tf.constant([0.]), tf.constant([0.]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sonnet/python/ops/resampler.py", line 65, in resampler
    raise ImportError("_gen_resampler could not be imported.")
ImportError: _gen_resampler could not be imported.


$ cd  # out from sonnet source directory.
$ python

>>> import sonnet as snt
>>> import tensorflow as tf
>>> snt.resampler(tf.constant([0.]), tf.constant([0.]))
<tf.Tensor 'resampler/Resampler:0' shape=(1,) dtype=float32>

**Comment by kosklain** [comment] 2017-05-25 13:28
Duplicate of #25 . Also, as pointed out, please move out of the sonnet to import it, as you might be importing only the python dependencies (a fix for this use case is coming in the following days).

**Closed by kosklain** 2017-05-25 13:28 UTC
